SELECT
     'echo '||GROUP_CONCAT( COLUMN_NAME Order by ORDINAL_POSITION SEPARATOR ';' )||'> '||TABLE_NAME||'.csv'
FROM
     INFORMATION_SCHEMA.SYSTEM_COLUMNS
WHERE
     TABLE_SCHEM = 'PUBLIC'
GROUP BY
     TABLE_NAME