SELECT
     ref.CONSTRAINT_NAME AS FK_NAME,
     'INNER' AS JOIN_TYPE,
     ref.TABLE_SCHEMA AS OWNER, 
     ref.TABLE_NAME,
     ref.COLUMN_NAME,
     ref.REFERENCED_TABLE_SCHEMA AS PKTABLE_OWNER,
     ref.REFERENCED_TABLE_NAME AS PKTABLE_NAME,
     '' AS PKTABLE_ALIAS,
     ref.REFERENCED_COLUMN_NAME AS PKCOLUMN_NAME,
     'na' AS COMMENT
FROM
     information_schema.KEY_COLUMN_USAGE ref
WHERE
     ref.CONSTRAINT_NAME != 'PRIMARY'
and ref.REFERENCED_COLUMN_NAME is not null
ORDER BY
     ref.ORDINAL_POSITION ASC