SELECT
     DBA_CONSTRAINTS.OWNER,
     DBA_CONSTRAINTS.TABLE_NAME,
     DBA_CONSTRAINTS.CONSTRAINT_NAME,
     DBA_CONSTRAINTS.CONSTRAINT_TYPE,
     DBA_CONS_COLUMNS.POSITION,
     DBA_CONS_COLUMNS.COLUMN_NAME,
     DBA_CONSTRAINTS.SEARCH_CONDITION,
     DBA_CONSTRAINTS.R_OWNER,
     DBA_CONSTRAINTS.R_CONSTRAINT_NAME,
     DBA_CONSTRAINTS.STATUS,
     DBA_CONSTRAINTS.VALIDATED
FROM
     DBA_CONS_COLUMNS RIGHT OUTER JOIN DBA_CONSTRAINTS ON DBA_CONS_COLUMNS.OWNER = DBA_CONSTRAINTS.OWNER
     AND DBA_CONS_COLUMNS.CONSTRAINT_NAME = DBA_CONSTRAINTS.CONSTRAINT_NAME
WHERE
     DBA_CONSTRAINTS.TABLE_NAME LIKE '%'
 AND DBA_CONSTRAINTS.CONSTRAINT_TYPE IN ('P','C','U','R')
 AND DBA_CONSTRAINTS.OWNER = 'SYSTEM'
ORDER BY
     DBA_CONSTRAINTS.OWNER ASC,
     DBA_CONSTRAINTS.TABLE_NAME ASC,
     DBA_CONSTRAINTS.CONSTRAINT_NAME ASC,
     DBA_CONS_COLUMNS.POSITION ASC