CREATE TABLE SOURCE (
    SOURCE_ID  INTEGER NOT NULL
);
ALTER TABLE SOURCE ADD CONSTRAINT PK_SOURCE PRIMARY KEY (SOURCE_ID);

CREATE TABLE DIM1 (
    ID         INTEGER NOT NULL,
    SOURCE_ID  INTEGER
);
ALTER TABLE DIM1 ADD CONSTRAINT PK_DIM1 PRIMARY KEY (ID);
--ALTER TABLE DIM1 ADD CONSTRAINT FK_DIM1_2 FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID);

CREATE TABLE DIM2 (
    ID         INTEGER NOT NULL,
    SOURCE_ID  INTEGER
);
ALTER TABLE DIM2 ADD CONSTRAINT PK_DIM2 PRIMARY KEY (ID);
--ALTER TABLE DIM2 ADD CONSTRAINT FK_DIM2_2 FOREIGN KEY (SOURCE_ID) REFERENCES SOURCE (SOURCE_ID);

CREATE TABLE FACT (
    ID   INTEGER NOT NULL,
    ID1  INTEGER,
    ID2  INTEGER
);

ALTER TABLE FACT ADD CONSTRAINT PK_FACT PRIMARY KEY (ID);
--ALTER TABLE FACT ADD CONSTRAINT FK_FACT_2 FOREIGN KEY (ID1) REFERENCES DIM1 (ID);
--ALTER TABLE FACT ADD CONSTRAINT FK_FACT_3 FOREIGN KEY (ID2) REFERENCES DIM2 (ID);

insert into source values (1);
insert into source values (2);

insert into dim1 values (1,1);
insert into dim1 values (2,1);

insert into dim2 values (1,1);
insert into dim2 values (2,2);
insert into dim2 values (3,2);

insert into fact values (1,1,1);
insert into fact values (2,1,2);
insert into fact values (3,2,1);
insert into fact values (4,2,2);
insert into fact values (5,2,3);
